function Send-JsonPayload {
    param (
        [Parameter(Mandatory)]
        [string]$Url,

        [Parameter(Mandatory)]
        [hashtable]$Payload,

        [Parameter(Mandatory)]
        [int]$depth,

        [string]$ContentType = "application/json"
    )

    try {
        # แปลง Payload เป็น JSON string
        $jsonBody = $Payload | ConvertTo-Json -Depth $depth -Compress

        Write-Host "Sending JSON to $Url..."
        Write-Host $jsonBody

        # ใช้ Invoke-WebRequest เพื่อให้ได้ Response object ที่มี StatusCode
        $response = Invoke-WebRequest -Uri $Url -Method Post -Body $jsonBody -ContentType $ContentType -ErrorAction Stop

        # คืนค่า StatusCode (ตัวเลข เช่น 200)
        return $response.StatusCode
    }
    catch {
        if ($_.Exception.Response -ne $null) {
            return $_.Exception.Response.StatusCode.Value__
        } else {
            Write-Error "Error sending data: $_"
            return -1  # ใช้ -1 เป็นตัวบ่งชี้ว่าไม่มี response code (เช่น network error)
        }
    }
}


$d = @"
{
  "ip": 0,
  "data": [
    {
      "start_date": "2025-09-04",
      "start_time": "09:32:24",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:33:48",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 1.4,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:19:02",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:35:10",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 16.13,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:34:00",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:36:19",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.32,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:34:01",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:36:19",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.3,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:34:00",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:36:19",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.32,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:37:29",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:40:16",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.78,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:37:29",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:40:16",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.78,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:42:42",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:45:00",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.3,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:42:42",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:45:00",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.3,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:42:41",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:45:00",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.32,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:18:33",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:46:07",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 27.57,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:18:37",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:46:07",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 27.5,
      "host": "apichart.c",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:18:37",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:46:07",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 27.5,
      "host": "apichart.c",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:18:37",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:46:07",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 27.5,
      "host": "apichart.c",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:18:37",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:46:07",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 27.5,
      "host": "apichart.c",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:18:37",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:46:07",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 27.5,
      "host": "apichart.c",
      "module": "af_compensator_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:51:31",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:53:52",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.35,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:51:31",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:53:52",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.35,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:51:31",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:53:52",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.35,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:56:09",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:58:37",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.47,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:56:09",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:58:37",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.47,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:56:08",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "09:58:37",
      "end_hours": "09",
      "end_action": "IN",
      "duration_minutes": 2.48,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:13:55",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:14:04",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 0.15,
      "host": "ah.autoform01",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:13:55",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:14:04",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 0.15,
      "host": "ah.autoform01",
      "module": "af_workspace_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:40:49",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:31:24",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 50.58,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:46:25",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:31:24",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 44.98,
      "host": "apichart.c",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:46:25",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:31:24",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 44.98,
      "host": "apichart.c",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:46:25",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:31:24",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 44.98,
      "host": "apichart.c",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:46:25",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:31:24",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 44.98,
      "host": "apichart.c",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:46:25",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:31:24",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 44.98,
      "host": "apichart.c",
      "module": "af_compensator_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:15:45",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:34:51",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 19.1,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:15:45",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:34:51",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 19.1,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:35:02",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:37:25",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 2.38,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:35:02",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:37:25",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 2.38,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:35:01",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:37:25",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 2.4,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:31:29",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:37:57",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 6.47,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:31:32",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:37:57",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 6.42,
      "host": "apichart.c",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:31:32",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:37:57",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 6.42,
      "host": "apichart.c",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:31:32",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:37:57",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 6.42,
      "host": "apichart.c",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:31:32",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:37:57",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 6.42,
      "host": "apichart.c",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:31:32",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:37:57",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 6.42,
      "host": "apichart.c",
      "module": "af_compensator_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:37:36",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:44:27",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 6.85,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:37:36",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:44:27",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 6.85,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:37:35",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "10:44:27",
      "end_hours": "10",
      "end_action": "IN",
      "duration_minutes": 6.87,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:59:34",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:02:03",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 2.48,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:59:35",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:02:03",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 2.47,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:59:34",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:02:03",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 2.48,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:41:11",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:10:37",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 29.43,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:06:59",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:26:40",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 19.68,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:07:00",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:26:40",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 19.67,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:16:55",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:28:23",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 11.47,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:17:39",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:28:23",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 10.73,
      "host": "apichart.c",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:17:39",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:28:23",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 10.73,
      "host": "apichart.c",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:17:39",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:28:23",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 10.73,
      "host": "apichart.c",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:17:39",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:28:23",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 10.73,
      "host": "apichart.c",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:17:39",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:28:23",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 10.73,
      "host": "apichart.c",
      "module": "af_compensator_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:26:58",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:29:29",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 2.52,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:26:59",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:29:29",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 2.5,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:26:58",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:29:29",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 2.52,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:29:30",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:29:59",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 0.48,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:29:30",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:29:59",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 0.48,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:29:29",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:29:59",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 0.5,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:57:04",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "11:48:18",
      "end_hours": "11",
      "end_action": "IN",
      "duration_minutes": 111.23,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:48:16",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:00:53",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 12.62,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:48:16",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:00:53",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 12.62,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:48:16",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:00:53",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 12.62,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:00:54",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:12:43",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 11.82,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:00:54",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:12:43",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 11.82,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:00:53",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:12:43",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 11.83,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:12:45",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:16:16",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 3.52,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:12:45",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:16:16",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 3.52,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:12:43",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:16:16",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 3.55,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:16:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:17:51",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.57,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:16:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:17:51",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.57,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:16:16",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:17:51",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.58,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:22:43",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:24:04",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 61.35,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:28:30",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:24:04",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 55.57,
      "host": "apichart.c",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:28:30",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:24:04",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 55.57,
      "host": "apichart.c",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:28:30",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:24:04",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 55.57,
      "host": "apichart.c",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:28:30",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:24:04",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 55.57,
      "host": "apichart.c",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:28:30",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:24:04",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 55.57,
      "host": "apichart.c",
      "module": "af_compensator_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:17:52",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:30:05",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 12.22,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:17:52",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:30:05",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 12.22,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:17:51",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:30:05",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 12.23,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:40:14",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:43:49",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 3.58,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:40:14",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:43:49",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 3.58,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:40:13",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:43:49",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 3.6,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:43:54",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:45:26",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.53,
      "host": "system",
      "module": "af_trim_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:43:54",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:45:26",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.53,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:45:29",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:47:04",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.58,
      "host": "system",
      "module": "af_trim_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:45:29",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:47:04",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.58,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:47:07",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:48:40",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.55,
      "host": "system",
      "module": "af_trim_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:47:07",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:48:40",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.55,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:48:43",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:50:15",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.53,
      "host": "system",
      "module": "af_trim_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:48:44",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:50:15",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 1.52,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:43:49",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:50:16",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 6.45,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:43:49",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:50:16",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 6.45,
      "host": "system",
      "module": "af_trim_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:43:49",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:50:19",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 6.5,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:43:49",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:50:19",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 6.5,
      "host": "system",
      "module": "af_trim_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:43:49",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "12:50:19",
      "end_hours": "12",
      "end_action": "IN",
      "duration_minutes": 6.5,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:51:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:03:22",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 12.08,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:51:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:03:22",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 12.08,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:51:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:03:23",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 12.1,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:03:23",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:04:50",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 1.45,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:03:24",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:04:50",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 1.43,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:03:23",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:04:50",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 1.45,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:04:51",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:06:16",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 1.42,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:04:51",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:06:16",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 1.42,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:04:50",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:06:16",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 1.43,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:51:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:14:24",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 23.12,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:51:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:14:24",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 23.12,
      "host": "apichart.c",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:51:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:14:24",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 23.12,
      "host": "apichart.c",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:51:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:14:24",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 23.12,
      "host": "apichart.c",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:51:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:14:24",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 23.12,
      "host": "apichart.c",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "12:51:17",
      "start_hours": "12",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:14:24",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 23.12,
      "host": "apichart.c",
      "module": "af_compensator_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:10:40",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:19:32",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 128.87,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:13:53",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:25:54",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 12.02,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:13:53",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:25:54",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 12.02,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:13:53",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:25:55",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 12.03,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:31:32",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:33:30",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 1.97,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:31:32",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:33:30",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 1.97,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "08:40:36",
      "start_hours": "08",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:39:01",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 298.42,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:19:06",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:39:01",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 259.92,
      "host": "piyaphong.t",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:19:06",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:39:01",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 259.92,
      "host": "piyaphong.t",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:19:06",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:39:01",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 259.92,
      "host": "piyaphong.t",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "09:19:06",
      "start_hours": "09",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:39:01",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 259.92,
      "host": "piyaphong.t",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "10:28:40",
      "start_hours": "10",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:44:04",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 195.4,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:39:06",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:44:04",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 4.97,
      "host": "piyaphong.t",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:39:06",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:44:04",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 4.97,
      "host": "piyaphong.t",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:39:06",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:44:04",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 4.97,
      "host": "piyaphong.t",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:39:06",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "13:44:04",
      "end_hours": "13",
      "end_action": "IN",
      "duration_minutes": 4.97,
      "host": "piyaphong.t",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:37:40",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:12:13",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 34.55,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:37:41",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:12:13",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 34.53,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:37:40",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:12:13",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 34.55,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:12:14",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:16:59",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 4.75,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:12:15",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:16:59",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 4.73,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:12:13",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:16:59",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 4.77,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:17:46",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:19:42",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 1.93,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:17:46",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:19:42",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 1.93,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:17:44",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:19:43",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 1.98,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:19:59",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:21:06",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 1.12,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:20:00",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:21:06",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 1.1,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:19:58",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:21:06",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 1.13,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:04:46",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:24:31",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 19.75,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:39:10",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:28:08",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 48.97,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:24:17",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:35:54",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 11.62,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:24:17",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:35:54",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 11.62,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:24:16",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:35:54",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 11.63,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:36:10",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:37:20",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 1.17,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:36:10",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:37:21",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 1.18,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:36:09",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:37:21",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 1.2,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:07:46",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:42:30",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 34.73,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:40:14",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:43:05",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 2.85,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:40:15",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:43:05",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 2.83,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:47:31",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:59:08",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 11.62,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:47:31",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:59:08",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 11.62,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:47:30",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "14:59:08",
      "end_hours": "14",
      "end_action": "IN",
      "duration_minutes": 11.63,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:08:05",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "15:12:45",
      "end_hours": "15",
      "end_action": "IN",
      "duration_minutes": 4.67,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:08:05",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "15:12:45",
      "end_hours": "15",
      "end_action": "IN",
      "duration_minutes": 4.67,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:31:51",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "15:36:39",
      "end_hours": "15",
      "end_action": "IN",
      "duration_minutes": 4.8,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:31:52",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "15:36:39",
      "end_hours": "15",
      "end_action": "IN",
      "duration_minutes": 4.78,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:48:50",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "15:50:52",
      "end_hours": "15",
      "end_action": "IN",
      "duration_minutes": 2.03,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:48:51",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "15:50:52",
      "end_hours": "15",
      "end_action": "IN",
      "duration_minutes": 2.02,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:08:23",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "15:52:45",
      "end_hours": "15",
      "end_action": "IN",
      "duration_minutes": 44.37,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:57:44",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:06:16",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 8.53,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:57:45",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:06:16",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 8.52,
      "host": "system",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:57:44",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:06:17",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 8.55,
      "host": "system",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:06:59",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:08:18",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 1.32,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:06:59",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:08:18",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 1.32,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:06:58",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:08:18",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 1.33,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:13:24",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:15:35",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 2.18,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:13:25",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:15:35",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 2.17,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:13:24",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:15:35",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 2.18,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:22:31",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:24:30",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 1.98,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:22:31",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:24:30",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 1.98,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:22:30",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:24:31",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 2.02,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:20:41",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:53:59",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 33.3,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "11:48:21",
      "start_hours": "11",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:55:06",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 306.75,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:44:10",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:55:06",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 190.93,
      "host": "piyaphong.t",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:44:10",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:55:06",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 190.93,
      "host": "piyaphong.t",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:44:10",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:55:06",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 190.93,
      "host": "piyaphong.t",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:44:10",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "16:55:06",
      "end_hours": "16",
      "end_action": "IN",
      "duration_minutes": 190.93,
      "host": "piyaphong.t",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:50:50",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "17:01:22",
      "end_hours": "17",
      "end_action": "IN",
      "duration_minutes": 190.53,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:55:12",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "17:01:22",
      "end_hours": "17",
      "end_action": "IN",
      "duration_minutes": 6.17,
      "host": "piyaphong.t",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:55:12",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "17:01:22",
      "end_hours": "17",
      "end_action": "IN",
      "duration_minutes": 6.17,
      "host": "piyaphong.t",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:55:12",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "17:01:22",
      "end_hours": "17",
      "end_action": "IN",
      "duration_minutes": 6.17,
      "host": "piyaphong.t",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "16:55:12",
      "start_hours": "16",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "17:01:22",
      "end_hours": "17",
      "end_action": "IN",
      "duration_minutes": 6.17,
      "host": "piyaphong.t",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "14:28:19",
      "start_hours": "14",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "17:01:36",
      "end_hours": "17",
      "end_action": "IN",
      "duration_minutes": 153.28,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "17:05:25",
      "start_hours": "17",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "17:08:06",
      "end_hours": "17",
      "end_action": "IN",
      "duration_minutes": 2.68,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "17:05:26",
      "start_hours": "17",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "17:08:06",
      "end_hours": "17",
      "end_action": "IN",
      "duration_minutes": 2.67,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "17:51:35",
      "start_hours": "17",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "17:53:41",
      "end_hours": "17",
      "end_action": "IN",
      "duration_minutes": 2.1,
      "host": "apichart.c",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "17:51:36",
      "start_hours": "17",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "17:53:41",
      "end_hours": "17",
      "end_action": "IN",
      "duration_minutes": 2.08,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "18:12:51",
      "start_hours": "18",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:21:08",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 8.28,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "18:12:52",
      "start_hours": "18",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:21:08",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 8.27,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "18:22:24",
      "start_hours": "18",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:31:10",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 8.77,
      "host": "piyaphong.t",
      "module": "af_solver_addon",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "18:22:25",
      "start_hours": "18",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:31:10",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 8.75,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "17:07:20",
      "start_hours": "17",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:52:30",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 105.17,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "18:07:22",
      "start_hours": "18",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:57:56",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 50.57,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "15:36:23",
      "start_hours": "15",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:58:08",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 201.75,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:22:04",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:58:19",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 336.25,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:22:09",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:58:19",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 336.17,
      "host": "apichart.c",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:22:09",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:58:19",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 336.17,
      "host": "apichart.c",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:22:09",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:58:19",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 336.17,
      "host": "apichart.c",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:22:09",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:58:19",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 336.17,
      "host": "apichart.c",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "13:22:09",
      "start_hours": "13",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "18:58:19",
      "end_hours": "18",
      "end_action": "IN",
      "duration_minutes": 336.17,
      "host": "apichart.c",
      "module": "af_compensator_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "17:01:28",
      "start_hours": "17",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:18:41",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 137.22,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "17:01:33",
      "start_hours": "17",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:18:41",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 137.13,
      "host": "piyaphong.t",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "17:01:33",
      "start_hours": "17",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:18:41",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 137.13,
      "host": "piyaphong.t",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "17:01:33",
      "start_hours": "17",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:18:41",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 137.13,
      "host": "piyaphong.t",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "17:01:33",
      "start_hours": "17",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:18:41",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 137.13,
      "host": "piyaphong.t",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:25:58",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:27:54",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 1.93,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:30:13",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:48:30",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 18.28,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:30:20",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:48:30",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 18.17,
      "host": "apichart.c",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:30:20",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:48:30",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 18.17,
      "host": "apichart.c",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:30:20",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:48:30",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 18.17,
      "host": "apichart.c",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:30:20",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:48:30",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 18.17,
      "host": "apichart.c",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:30:20",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:48:30",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 18.17,
      "host": "apichart.c",
      "module": "af_compensator_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:33:14",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:48:35",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 15.35,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:48:45",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:49:43",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 0.97,
      "host": "apichart.c",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:49:11",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:49:43",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 0.53,
      "host": "apichart.c",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:49:11",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:49:43",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 0.53,
      "host": "apichart.c",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:49:11",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:49:43",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 0.53,
      "host": "apichart.c",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:49:11",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:49:43",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 0.53,
      "host": "apichart.c",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:49:11",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:49:43",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 0.53,
      "host": "apichart.c",
      "module": "af_compensator_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:28:06",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:58:12",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 30.1,
      "host": "piyaphong.t",
      "module": "af_company_string",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:28:12",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:58:12",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 30.0,
      "host": "piyaphong.t",
      "module": "af_autoform_seat_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:28:12",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:58:12",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 30.0,
      "host": "piyaphong.t",
      "module": "af_explorer_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:28:12",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:58:12",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 30.0,
      "host": "piyaphong.t",
      "module": "af_stampingadviser_addon_nu",
      "username": null,
      "version": "5.0"
    },
    {
      "start_date": "2025-09-04",
      "start_time": "19:28:12",
      "start_hours": "19",
      "start_action": "OUT",
      "end_date": "2025-09-04",
      "end_time": "19:58:12",
      "end_hours": "19",
      "end_action": "IN",
      "duration_minutes": 30.0,
      "host": "piyaphong.t",
      "module": "af_diedesigner_addon_nu",
      "username": null,
      "version": "5.0"
    }
  ],
  "product": "autoform"
}
"@

   $Url = "http://localhost/testing/"
    # เรียก function ส่ง JSON
     $response = Invoke-WebRequest -Uri $Url -Method Post -Body $d -ContentType "application/json" -ErrorAction Sto
    Write-Host "Response from server: $response"