version: '3.8'

services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    image: playwright-test:latest_build
    volumes:
      - .:/app
    working_dir: /app
    command: ["./cmd.sh"]